User.create!([
  { first_name: "Gina", last_name: "Mirando", email: "Gina@test.com", password: "password" },
  { first_name: "World Wide", last_name: "Web", email: "Weber@test.com", password: "password" },
  { first_name: "Joey", last_name: "Bag of donuts", email: "Joey@test.com", password: "password" },
  { first_name: "Alison", last_name: "Dec", email: "Alison@test.com", password: "password" },
])

Line.create!([
  { name: "blue" },
  { name: "brown" },
  { name: "red" },
  { name: "green" },
  { name: "orange" },
  { name: "purple" },
  { name: "pink" },
  { name: "yellow" },
])

Stop.create!([
  { name: "O'hare", id: 40890, line_id: "1", stop_id: "101", is_accessible: true, towards_loop: false },
  { name: "Rosemont", id: 40820, line_id: "1", stop_id: "102", is_accessible: true, towards_loop: false },
  { name: "Cumberland", id: 40230, line_id: "1", stop_id: "103", is_accessible: true, towards_loop: false },
  { name: "Harlem", id: 40750, line_id: "1", stop_id: "104", is_accessible: true, towards_loop: false },
  { name: "Jefferson Park", id: 41280, line_id: "1", stop_id: "105", is_accessible: true, towards_loop: false },
  { name: "Montrose", id: 41330, line_id: "1", stop_id: "106", is_accessible: false, towards_loop: false },
  { name: "Irving Park", id: 40550, line_id: "1", stop_id: "107", is_accessible: false, towards_loop: false },
  { name: "Addison", id: 41440, line_id: "1", stop_id: "108", is_accessible: true, towards_loop: false },
  { name: "Belmont", id: 41320, line_id: "1", stop_id: "109", is_accessible: false, towards_loop: false },
  { name: "Logan Square", id: 41020, line_id: "1", stop_id: "110", is_accessible: true, towards_loop: false },
  { name: "California", id: 40570, line_id: "1", stop_id: "111", is_accessible: false, towards_loop: false },
  { name: "Western", id: 40670, line_id: "1", stop_id: "112", is_accessible: true, towards_loop: false },
  { name: "Damen", id: 40590, line_id: "1", stop_id: "113", is_accessible: false, towards_loop: false },
  { name: "Division", id: 40320, line_id: "1", stop_id: "114", is_accessible: false, towards_loop: false },
  { name: "Chicago", id: 41410, line_id: "1", stop_id: "115", is_accessible: false, towards_loop: false },
  { name: "Grand", id: 40490, line_id: "1", stop_id: "116", is_accessible: false, towards_loop: false },
  { name: "Clark/Lake", id: 40380, line_id: "1", stop_id: "117", is_accessible: true, towards_loop: false },
  { name: "Washington", id: 40370, line_id: "1", stop_id: "118", is_accessible: false, towards_loop: false },
  { name: "Monroe", id: 40790, line_id: "1", stop_id: "119", is_accessible: false, towards_loop: false },
  { name: "Jackson", id: 40070, line_id: "1", stop_id: "120", is_accessible: true, towards_loop: false },
  { name: "LaSalle", id: 41340, line_id: "1", stop_id: "121", is_accessible: false, towards_loop: false },
  { name: "Clinton", id: 40430, line_id: "1", stop_id: "122", is_accessible: false, towards_loop: false },
  { name: "UIC-Halsted", id: 40350, line_id: "1", stop_id: "123", is_accessible: true, towards_loop: false },
  { name: "Racine", id: 40470, line_id: "1", stop_id: "124", is_accessible: false, towards_loop: false },
  { name: "Illinois Medical District", id: 40810, line_id: "1", stop_id: "125", is_accessible: true, towards_loop: false },
  { name: "Western (Forest Park Branch)", id: 40220, line_id: "1", stop_id: "126", is_accessible: false, towards_loop: false },
  { name: "Kedzie-Homan", id: 40250, line_id: "1", stop_id: "127", is_accessible: true, towards_loop: false },
  { name: "Pulaski", id: 40920, line_id: "1", stop_id: "128", is_accessible: false, towards_loop: false },
  { name: "Cicero", id: 40970, line_id: "1", stop_id: "129", is_accessible: false, towards_loop: false },
  { name: "Austin", id: 40010, line_id: "1", stop_id: "130", is_accessible: false, towards_loop: false },
  { name: "Oak Park", id: 40180, line_id: "1", stop_id: "131", is_accessible: false, towards_loop: false },
  { name: "Harlem (Forest Park Branch)", id: 40980, line_id: "1", stop_id: "132", is_accessible: false, towards_loop: false },
  { name: "Forest Park", id: 40390, line_id: "1", stop_id: "133", is_accessible: true, towards_loop: false },

# { name: "Kimball", id: 0, line_id: "2", stop_id: "101", is_accessible: true, towards_loop: false },
# { name: "Kedzie", parent_id: 0, line_id: "2", stop_id: "102", is_accessible: true, towards_loop: false },
# { name: "Francisco", parent_id: 0, line_id: "2", stop_id: "103", is_accessible: true, towards_loop: false },
# { name: "Rockwell", parent_id: 0, line_id: "2", stop_id: "104", is_accessible: true, towards_loop: false },
# { name: "Western", parent_id: 0, line_id: "2", stop_id: "105", is_accessible: true, towards_loop: false },
# { name: "Damen", parent_id: 0, line_id: "2", stop_id: "106", is_accessible: true, towards_loop: false },
# { name: "Montrose", parent_id: 0, line_id: "2", stop_id: "107", is_accessible: true, towards_loop: false },
# { name: "Irving Park", parent_id: 0, line_id: "2", stop_id: "108", is_accessible: true, towards_loop: false },
# { name: "Addison", parent_id: 0, line_id: "2", stop_id: "109", is_accessible: true, towards_loop: false },
# { name: "Paulina", parent_id: 0, line_id: "2", stop_id: "110", is_accessible: true, towards_loop: false },
# { name: "Southport", parent_id: 0, line_id: "2", stop_id: "111", is_accessible: true, towards_loop: false },
# { name: "Belmont", parent_id: 0, line_id: "2", stop_id: "112", is_accessible: true, towards_loop: false },
# { name: "Wellington", parent_id: 0, line_id: "2", stop_id: "113", is_accessible: true, towards_loop: false },
# { name: "Diversey", parent_id: 0, line_id: "2", stop_id: "114", is_accessible: true, towards_loop: false },
# { name: "Fullerton", parent_id: 0, line_id: "2", stop_id: "115", is_accessible: true, towards_loop: false },
# { name: "Armitage", parent_id: 0, line_id: "2", stop_id: "116", is_accessible: true, towards_loop: false },
# { name: "Sedgwick", parent_id: 0, line_id: "2", stop_id: "117", is_accessible: true, towards_loop: false },
# { name: "Chicago", parent_id: 0, line_id: "2", stop_id: "118", is_accessible: true, towards_loop: false },
# { name: "Merchandise Mart", parent_id: 0, line_id: "2", stop_id: "119", is_accessible: true, towards_loop: false },
# { name: "Washington/Wells", parent_id: 0, line_id: "2", stop_id: "120", is_accessible: true, towards_loop: false },
# { name: "Quincy", parent_id: 0, line_id: "2", stop_id: "121", is_accessible: true, towards_loop: false },
# { name: "LaSalle/Van Buren", parent_id: 0, line_id: "2", stop_id: "122", is_accessible: false, towards_loop: false },
# { name: "Harold Washington Library-State/Van Buren", parent_id: 0, line_id: "2", stop_id: "123", is_accessible: true, towards_loop: false },
# { name: "Adams/Wabash", parent_id: 0, line_id: "2", stop_id: "124", is_accessible: false, towards_loop: false },
# { name: "Washington/Wabash", parent_id: 0, line_id: "2", stop_id: "125", is_accessible: true, towards_loop: false },
# { name: "State/Lake", parent_id: 0, line_id: "2", stop_id: "126", is_accessible: false, towards_loop: false },
# { name: "Clark/Lake", parent_id: 0, line_id: "2", stop_id: "127", is_accessible: true, towards_loop: false },
])
