User.create!([
  {first_name: "Gina", last_name: "Mirando", email: "Gina@test.com", password: "password"},
  {first_name: "Joey", last_name: "Bag of donuts", email: "Joey@test.com", password: "password"},
  {first_name: "Alison", last_name: "Dec", email: "Alison@test.com", password: "password"},
])

Line.create!([
  {color: "blue"}, 
  {color: "brown"}, 
  {color: "red"},
  {color: "green"}, 
  {color: "orange"},
  {color: "purple"},
  {color: "pink"}, 
  {color: "yellow"}
])

Stop.create!([
  {name: "O'hare", line_id: "1", stop_id: "101", is_accessible: true, towards_loop: false},
  {name: "Rosemont", line_id: "1", stop_id: "102", is_accessible: true, towards_loop: false},
  {name: "Cumberland", line_id: "1", stop_id: "103", is_accessible: true, towards_loop: false},
  {name: "Harlem", line_id: "1", stop_id: "104", is_accessible: true, towards_loop: false},
  {name: "Jefferson Park", line_id: "1", stop_id: "105", is_accessible: true, towards_loop: false},
  {name: "Montrose", line_id: "1", stop_id: "106", is_accessible: false, towards_loop: false},
  {name: "Irving Park", line_id: "1", stop_id: "107", is_accessible: false, towards_loop: false},
  {name: "Addison", line_id: "1", stop_id: "108", is_accessible: true, towards_loop: false},
  {name: "Belmont", line_id: "1", stop_id: "109", is_accessible: false, towards_loop: false},
  {name: "Logan Square", line_id: "1", stop_id: "110", is_accessible: true, towards_loop: false},
  {name: "California", line_id: "1", stop_id: "111", is_accessible: false, towards_loop: false},
  {name: "Western", line_id: "1", stop_id: "112", is_accessible: true, towards_loop: false},
  {name: "Damen", line_id: "1", stop_id: "113", is_accessible: false, towards_loop: false},
  {name: "Division", line_id: "1", stop_id: "114", is_accessible: false, towards_loop: false},
  {name: "Chicago", line_id: "1", stop_id: "115", is_accessible: false, towards_loop: false},
  {name: "Grand", line_id: "1", stop_id: "116", is_accessible: false, towards_loop: false},
  {name: "Clark/Lake", line_id: "1", stop_id: "117", is_accessible: true, towards_loop: false},
  {name: "Washington", line_id: "1", stop_id: "118", is_accessible: false, towards_loop: false},
  {name: "Monroe", line_id: "1", stop_id: "119", is_accessible: false, towards_loop: false},
  {name: "Jackson", line_id: "1", stop_id: "120", is_accessible: true, towards_loop: false},
  {name: "LaSalle", line_id: "1", stop_id: "121", is_accessible: false, towards_loop: false},
  {name: "Clinton", line_id: "1", stop_id: "122", is_accessible: false, towards_loop: false},
  {name: "UIC-Halsted", line_id: "1", stop_id: "123", is_accessible: true, towards_loop: false},
  {name: "Racine", line_id: "1", stop_id: "124", is_accessible: false, towards_loop: false},
  {name: "Illinois Medical District", line_id: "1", stop_id: "125", is_accessible: true, towards_loop: false},
  {name: "Western (Forest Park Branch)", line_id: "1", stop_id: "126", is_accessible: false, towards_loop: false},
  {name: "Kedzie-Homan", line_id: "1", stop_id: "127", is_accessible: true, towards_loop: false},
  {name: "Pulaski", line_id: "1", stop_id: "128", is_accessible: false, towards_loop: false},
  {name: "Cicero", line_id: "1", stop_id: "129", is_accessible: false, towards_loop: false},
  {name: "Austin", line_id: "1", stop_id: "130", is_accessible: false, towards_loop: false},
  {name: "Oak Park", line_id: "1", stop_id: "131", is_accessible: false, towards_loop: false},
  {name: "Harlem (Forest Park Branch)", line_id: "1", stop_id: "132", is_accessible: false, towards_loop: false},
  {name: "Forest Park", line_id: "1", stop_id: "133", is_accessible: true, towards_loop: false},

  {name: "Kimball", line_id: "2", stop_id: "101", is_accessible: true, towards_loop: false},
  {name: "Kedzie", line_id: "2", stop_id: "102", is_accessible: true, towards_loop: false},
  {name: "Francisco", line_id: "2", stop_id: "103", is_accessible: true, towards_loop: false},
  {name: "Rockwell", line_id: "2", stop_id: "104", is_accessible: true, towards_loop: false},
  {name: "Western", line_id: "2", stop_id: "105", is_accessible: true, towards_loop: false},
  {name: "Damen", line_id: "2", stop_id: "106", is_accessible: true, towards_loop: false},
  {name: "Montrose", line_id: "2", stop_id: "107", is_accessible: true, towards_loop: false},
  {name: "Irving Park", line_id: "2", stop_id: "108", is_accessible: true, towards_loop: false},
  {name: "Addison", line_id: "2", stop_id: "109", is_accessible: true, towards_loop: false},
  {name: "Paulina", line_id: "2", stop_id: "110", is_accessible: true, towards_loop: false},
  {name: "Southport", line_id: "2", stop_id: "111", is_accessible: true, towards_loop: false},
  {name: "Belmont", line_id: "2", stop_id: "112", is_accessible: true, towards_loop: false},
  {name: "Wellington", line_id: "2", stop_id: "113", is_accessible: true, towards_loop: false},
  {name: "Diversey", line_id: "2", stop_id: "114", is_accessible: true, towards_loop: false},
  {name: "Fullerton", line_id: "2", stop_id: "115", is_accessible: true, towards_loop: false},
  {name: "Armitage", line_id: "2", stop_id: "116", is_accessible: true, towards_loop: false},
  {name: "Sedgwick", line_id: "2", stop_id: "117", is_accessible: true, towards_loop: false},
  {name: "Chicago", line_id: "2", stop_id: "118", is_accessible: true, towards_loop: false},
  {name: "Merchandise Mart", line_id: "2", stop_id: "119", is_accessible: true, towards_loop: false},
  {name: "Washington/Wells", line_id: "2", stop_id: "120", is_accessible: true, towards_loop: false},
  {name: "Quincy", line_id: "2", stop_id: "121", is_accessible: true, towards_loop: false},
  {name: "LaSalle/Van Buren", line_id: "2", stop_id: "122", is_accessible: false, towards_loop: false},
  {name: "Harold Washington Library-State/Van Buren", line_id: "2", stop_id: "123", is_accessible: true, towards_loop: false},
  {name: "Adams/Wabash", line_id: "2", stop_id: "124", is_accessible: false, towards_loop: false},
  {name: "Washington/Wabash", line_id: "2", stop_id: "125", is_accessible: true, towards_loop: false},
  {name: "State/Lake", line_id: "2", stop_id: "126", is_accessible: false, towards_loop: false},
  {name: "Clark/Lake", line_id: "2", stop_id: "127", is_accessible: true, towards_loop: false},
])


